### ISSUE TITLE
Git code not tagged to correspond with npmjs.com?

### ISSUE THREAD

**Issue by mikehardy** [briankabiro/react-native-get-sms-android#28]
This is more of a question than an issue :-)

I see on npmjs.com that the package is being updated with the work here - last publish is 1.3.8 and recently: https://www.npmjs.com/package/rn-update-get-sms-android

However, I don't see any git tags or anything here, so I'm not sure what code is in which version? In the future could you `git tag vX.Y.Z` and `git push --tags` for the corresponding commit that you `npm publish` ? I would appreciate it, as I appreciate all the effort here :-). Thanks

**Comment by briankabiro** [comment]
Hey Mike. Thanks for flagging this.

I've been tagging versions through npm and not pushing them using git. I will definitely start doing this from now onwards.

Appreciate the pointers; I've managed to push them now so that's a start. 😃 

https://github.com/briankabiro/react-native-get-sms-android/releases

**Comment by mikehardy** [comment]
Fantastic - thanks
