### ISSUE TITLE
send and delete sms

### ISSUE THREAD

**Issue by ghost** [briankabiro/react-native-get-sms-android#5]
I'm going to send and delete my sms. i used this method to send sms
```
 let sms= SmsAndroid.autoSend("0966666622", "message", (fail) => {
            console.log("Failed with this error: " + fail)
        }, (success) => {
            console.log("SMS sent successfully ==>"+success);

        });
        console.log("second SMS sent successfully ==>"+sms);
```

and also used this method to delete sms
```
SmsAndroid.delete(1, (fail) => {
            console.log("Failed with this error: " + fail)
        }, (success) => {
            console.log("SMS deleted successfully");
        });
```

i get this error: Failed with this error: SMS not found****

i don't know how to get the sms id. in the autoSend to delete that sms.
Note: i pasted a fake number in the first delete argument!!

**Comment by davidstoneham** [comment]
Your first issue is the sms is not returned on a successful send when using the autoSend function. To get the sms detail and the id you need to perform list function. You can use the filters to only return the messages sent to the mobile number so ensure you only get the sms you want to delete.

When you do this list you'll receive the id of the sms which you can use to delete the sms using the delete function.

One quirk on Android is that the sms won't be able to delete the sms straight away. You will have to wait 1-2 seconds after sending or receiving an sms before it can be delete. This is due to the way android deals with storing text messages.

**Comment by husseinoj** [comment]
I do like this but i still get SMS not found error:
```
listSMS() {
        let filter = {
            address: ''
        };

        SmsAndroid.list(JSON.stringify(filter), (fail) => {
                console.log("Failed with this error: " + fail)
            },
            (count, smsList) => {
               /* console.log('Count: ', count);
                console.log('List: ', smsList);*/
                let arr = JSON.parse(smsList);
                arr.forEach(function(object){
                    if (object.address ==="+phone"){
                        console.log("Object: " + object._id);
                        SmsAndroid.delete( object._id, (fail) => {
                            console.log("Failed with this error: " + fail)
                        }, (success) => {
                            console.log("SMS deleted successfully"+success);
                        });
                    }
                })
            });
    }
```
The  if (object.address ==="+phone") condition is true and the message id is 251 but i get the error that it says SMS not found.
i also adding following permission to the android Manifest:

```
<uses-permission android:name="android.permission.READ_SMS" />
  <uses-permission android:name="android.permission.WRITE_SMS" />
  <uses-permission android:name="android.permission.SEND_SMS" />
```
but nothing has changed

**Comment by briankabiro** [comment]
@husseinoj 
did you make any progress?

**Comment by husseinoj** [comment]
what do u mean? did u delete a sms successfully?

**Comment by briankabiro** [comment]
@husseinoj yes

**Comment by husseinoj** [comment]
what version of android did u test? i tested on android version 7, and got the SMS not found

**Comment by davidstoneham** [comment]
@husseinoj i'm looking into this. I've had issues deleting SMS on android 6 and later and since the only error is SMS not found it's hard to track it down. I suspect the process has changed for deleting SMS in newer versions of android and hopefully it is still possible without setting your app as the default SMS app.

**Comment by davidstoneham** [comment]
@husseinoj apologies for getting to this so late. Unfortunately it's not possible to delete an SMS without being the default SMS application in android so that function will not work on android 6 and higher
